services:
  app:
    container_name: app
    build: ./
    ports:
      - 8080:8080
    env_file:
      - .env
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  db:
    image: postgres:15
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    expose:
      - 5432
    container_name: postgres
    env_file:
      - .env
    volumes:
      - db_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    networks:
      - app_network

volumes:
  db_postgres:

networks:
  app_network:
